   
services:
  web:
    build: .
    container_name: project02_skillsurgeAWS
    ports:
      - "9091:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: AWS-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: freelance_db
      MYSQL_USER: freelance_user
      MYSQL_PASSWORD: freelance_pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: AWS-phpmyadmin
    restart: always
    ports:
      - "9092:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db